export const colors = {
  background: "#FDF9F2",
  card: "#FFFFFF",
  cardShadow: "#D6D3CC",
  primary: "#5B6E5D",
  primaryPressed: "#4A5C4C",
  secondary: "#A8B5A0",
  textPrimary: "#2C2C2C",
  textSecondary: "#6B6B6B",
  textMuted: "#9A9A9A",
  badgeBreathing: "#D4E4D9",
  badgeBreathingText: "#3D6B4E",
  badgeFocus: "#D9DFF0",
  badgeFocusText: "#3D4E7A",
  badgeReflection: "#F0E4D4",
  badgeReflectionText: "#7A5E3D",
  border: "#E8E6E1",
  error: "#C45C5C",
  errorBackground: "#FDF0F0",
};
